In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

Cleaning the data 

In [2]:
df = pd.read_csv('healthcare-dataset-stroke-data.csv')

In [3]:
df.head(5)

id  gender   age  ...   bmi   smoking_status stroke
0   9046    Male  67.0  ...  36.6  formerly smoked      1
1  51676  Female  61.0  ...   NaN     never smoked      1
2  31112    Male  80.0  ...  32.5     never smoked      1
3  60182  Female  49.0  ...  34.4           smokes      1
4   1665  Female  79.0  ...  24.0     never smoked      1

[5 rows x 12 columns]

In [7]:
df = df.drop('id',axis=1)

gender   age  hypertension  ...   bmi   smoking_status stroke
0       Male  67.0             0  ...  36.6  formerly smoked      1
1     Female  61.0             0  ...   NaN     never smoked      1
2       Male  80.0             0  ...  32.5     never smoked      1
3     Female  49.0             0  ...  34.4           smokes      1
4     Female  79.0             1  ...  24.0     never smoked      1
...      ...   ...           ...  ...   ...              ...    ...
5105  Female  80.0             1  ...   NaN     never smoked      0
5106  Female  81.0             0  ...  40.0     never smoked      0
5107  Female  35.0             0  ...  30.6     never smoked      0
5108    Male  51.0             0  ...  25.6  formerly smoked      0
5109  Female  44.0             0  ...  26.2          Unknown      0

[5110 rows x 11 columns]

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   id                 5110 non-null   int64  
 1   gender             5110 non-null   object 
 2   age                5110 non-null   float64
 3   hypertension       5110 non-null   int64  
 4   heart_disease      5110 non-null   int64  
 5   ever_married       5110 non-null   object 
 6   work_type          5110 non-null   object 
 7   Residence_type     5110 non-null   object 
 8   avg_glucose_level  5110 non-null   float64
 9   bmi                4909 non-null   float64
 10  smoking_status     5110 non-null   object 
 11  stroke             5110 non-null   int64  
dtypes: float64(3), int64(4), object(5)
memory usage: 479.2+ KB


In [10]:
df.isnull().sum()

id                     0
gender                 0
age                    0
hypertension           0
heart_disease          0
ever_married           0
work_type              0
Residence_type         0
avg_glucose_level      0
bmi                  201
smoking_status         0
stroke                 0
dtype: int64

In [13]:
print(df[df['gender'] == 'Male']['bmi'].mean())
print(df[df['gender'] == 'Female']['bmi'].mean())

28.647936350074616
29.065757680359038


In [19]:
for i in range(len(df['bmi'])):
  if pd.isnull(df.at[i,'bmi']) == True:
      df.at[i,'bmi'] = 29
  

In [20]:
df.head(5)

id  gender   age  ...   bmi   smoking_status stroke
0   9046    Male  67.0  ...  36.6  formerly smoked      1
1  51676  Female  61.0  ...  29.0     never smoked      1
2  31112    Male  80.0  ...  32.5     never smoked      1
3  60182  Female  49.0  ...  34.4           smokes      1
4   1665  Female  79.0  ...  24.0     never smoked      1

[5 rows x 12 columns]

In [21]:
#Turning string data into numeric data
from sklearn.preprocessing import LabelEncoder
encodings_dictionary = dict()
for c in df.columns:
    if df[c].dtype == "object":
        encodings_dictionary[c] = LabelEncoder()
        df[c] = encodings_dictionary[c].fit_transform(df[c])

In [23]:

df = df.drop('id', axis = 1)
df.head(5)

gender   age  hypertension  ...   bmi  smoking_status  stroke
0       1  67.0             0  ...  36.6               1       1
1       0  61.0             0  ...  29.0               2       1
2       1  80.0             0  ...  32.5               2       1
3       0  49.0             0  ...  34.4               3       1
4       0  79.0             1  ...  24.0               2       1

[5 rows x 11 columns]

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   gender             5110 non-null   int64  
 1   age                5110 non-null   float64
 2   hypertension       5110 non-null   int64  
 3   heart_disease      5110 non-null   int64  
 4   ever_married       5110 non-null   int64  
 5   work_type          5110 non-null   int64  
 6   Residence_type     5110 non-null   int64  
 7   avg_glucose_level  5110 non-null   float64
 8   bmi                5110 non-null   float64
 9   smoking_status     5110 non-null   int64  
 10  stroke             5110 non-null   int64  
dtypes: float64(3), int64(8)
memory usage: 439.3 KB


Preproccesing

In [34]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

X = df.drop('stroke',axis=1)
y= df['stroke']

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

Model testing

In [35]:
from sklearn.svm import SVC

svm=SVC()
svm.fit(X_train, y_train)
predictions = svm.predict(X_test)

In [36]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test,predictions))
print(confusion_matrix(y_test,predictions))

              precision    recall  f1-score   support

           0       0.96      1.00      0.98       980
           1       0.00      0.00      0.00        42

    accuracy                           0.96      1022
   macro avg       0.48      0.50      0.49      1022
weighted avg       0.92      0.96      0.94      1022

[[980   0]
 [ 42   0]]


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [29]:
from sklearn.model_selection import GridSearchCV

param_grid = {'C':[0.5,1,10,100,1000], 'gamma':[0.1,0.01,0.001,0.0001,0.00001]}

grid = GridSearchCV(SVC(), param_grid, refit=True, verbose=True)

grid.fit(X_train,y_train)
grid_predictions = grid.predict(X_test)
print(classification_report(y_test,grid_predictions))
print(confusion_matrix(y_test,grid_predictions))

Fitting 5 folds for each of 25 candidates, totalling 125 fits


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done 125 out of 125 | elapsed:   51.1s finished


              precision    recall  f1-score   support

           0       0.95      1.00      0.98       976
           1       0.00      0.00      0.00        46

    accuracy                           0.95      1022
   macro avg       0.48      0.50      0.49      1022
weighted avg       0.91      0.95      0.93      1022

[[976   0]
 [ 46   0]]


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [37]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(X_train,y_train)
lr_predictions = lr.predict(X_test)
print(classification_report(y_test,lr_predictions))
print(confusion_matrix(y_test,lr_predictions))

              precision    recall  f1-score   support

           0       0.96      1.00      0.98       980
           1       0.00      0.00      0.00        42

    accuracy                           0.96      1022
   macro avg       0.48      0.50      0.49      1022
weighted avg       0.92      0.96      0.94      1022

[[980   0]
 [ 42   0]]


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [38]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier()
knn.fit(X_train, y_train)
knn_predictions = knn.predict(X_test)
print(classification_report(y_test,knn_predictions))
print(confusion_matrix(y_test,knn_predictions))

              precision    recall  f1-score   support

           0       0.96      1.00      0.98       980
           1       0.25      0.02      0.04        42

    accuracy                           0.96      1022
   macro avg       0.60      0.51      0.51      1022
weighted avg       0.93      0.96      0.94      1022

[[977   3]
 [ 41   1]]


In [32]:
from sklearn.feature_selection import RFECV
from sklearn.ensemble import RandomForestClassifier
m = RFECV(RandomForestClassifier(), scoring='accuracy')
m.fit(X_train, y_train)
m_predictions = m.predict(X_test)
print(classification_report(y_test,m_predictions))
print(confusion_matrix(y_test,m_predictions))

              precision    recall  f1-score   support

           0       0.95      1.00      0.98       976
           1       0.00      0.00      0.00        46

    accuracy                           0.95      1022
   macro avg       0.48      0.50      0.49      1022
weighted avg       0.91      0.95      0.93      1022

[[974   2]
 [ 46   0]]


In [40]:
rf = RandomForestClassifier()
rf.fit(X_train, y_train)
rf_predictions = rf.predict(X_test)
print(classification_report(y_test,rf_predictions))
print(confusion_matrix(y_test,rf_predictions))

              precision    recall  f1-score   support

           0       0.96      1.00      0.98       980
           1       0.00      0.00      0.00        42

    accuracy                           0.96      1022
   macro avg       0.48      0.50      0.49      1022
weighted avg       0.92      0.96      0.94      1022

[[980   0]
 [ 42   0]]


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [41]:
pip install tpot

     |████████████████████████████████| 87 kB 6.1 MB/s 
     |████████████████████████████████| 160 kB 44.3 MB/s 
     |████████████████████████████████| 173.5 MB 24 kB/s 
  Created wheel for stopit: filename=stopit-1.1.2-py3-none-any.whl size=11952 sha256=ca15117c84d59b28cf6e4000d833ade0c83082a63da83d00e7620895f362eac1
  Stored in directory: /root/.cache/pip/wheels/e2/d2/79/eaf81edb391e27c87f51b8ef901ecc85a5363dc96b8b8d71e3
Successfully built stopit
  Attempting uninstall: xgboost
    Found existing installation: xgboost 0.90
    Uninstalling xgboost-0.90:
      Successfully uninstalled xgboost-0.90


In [42]:
from tpot import TPOTClassifier
tpot = TPOTClassifier(max_time_mins=30, verbosity=2)
tpot.fit(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/externals/six.py:31: FutureWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", FutureWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.neighbors.base module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.neighbors. Anything that cannot be imported from sklearn.neighbors is now part of the private API.
  warnings.warn(message, FutureWarning)


Optimization Progress:   0%|          | 0/100 [00:00<?, ?pipeline/s]


Generation 1 - Current best internal CV score: 0.9496087121767574

Generation 2 - Current best internal CV score: 0.9496087121767574

Generation 3 - Current best internal CV score: 0.949853510218373

Generation 4 - Current best internal CV score: 0.949853510218373


TPOT closed during evaluation in one generation.


TPOT closed prematurely. Will use the current best pipeline.

Best pipeline: LogisticRegression(input_matrix, C=10.0, dual=False, penalty=l2)


TPOTClassifier(config_dict=None, crossover_rate=0.1, cv=5,
               disable_update_check=False, early_stop=None, generations=100,
               log_file=None, max_eval_time_mins=5, max_time_mins=30,
               memory=None, mutation_rate=0.9, n_jobs=1, offspring_size=None,
               periodic_checkpoint_folder=None, population_size=100,
               random_state=None, scoring=None, subsample=1.0, template=None,
               use_dask=False, verbosity=2, warm_start=False)